# Generated by Django 4.2.30 on 2026-05-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_main', models.BooleanField(default=False)),
                ('facilities', models.TextField(blank=True, help_text='Comma-separated list of facilities')),
                ('map_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['-is_main', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('population', models.CharField(blank=True, max_length=50)),
                ('cost_of_living', models.CharField(blank=True, help_text='e.g. AUD 1,800–2,500/month', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, help_text='Image filename in static/img/states/', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_name', models.CharField(blank=True, help_text='e.g. UNSW, ANU', max_length=50)),
                ('institution_type', models.CharField(choices=[('public', 'Public University'), ('private', 'Private University'), ('tafe', 'TAFE Institute'), ('private_provider', 'Private Provider')], default='public', max_length=20)),
                ('group_affiliation', models.CharField(choices=[('go8', 'Group of Eight (Go8)'), ('atn', 'Australian Technology Network (ATN)'), ('irua', 'Innovative Research Universities (IRU)'), ('raa', 'Regional Universities Australia'), ('none', 'Independent')], default='none', max_length=20)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('about', models.TextField(blank=True, help_text='Why choose this university')),
                ('ranking_qs', models.CharField(blank=True, help_text='e.g. #41 World', max_length=50)),
                ('ranking_times', models.CharField(blank=True, max_length=50)),
                ('total_students', models.CharField(blank=True, max_length=50)),
                ('international_students', models.CharField(blank=True, max_length=50)),
                ('cost_of_living', models.CharField(blank=True, help_text='e.g. AUD 1,800–2,500/month', max_length=100)),
                ('application_fee', models.CharField(blank=True, max_length=50)),
                ('official_website', models.URLField()),
                ('international_page', models.URLField(blank=True)),
                ('scholarship_page', models.URLField(blank=True)),
                ('application_portal', models.URLField(blank=True)),
                ('logo', models.CharField(blank=True, help_text='Logo filename', max_length=200)),
                ('image', models.CharField(blank=True, help_text='Campus image filename', max_length=200)),
                ('popular_courses', models.CharField(blank=True, help_text='Comma-separated popular courses', max_length=500)),
                ('internship_info', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='universities.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.state')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit-based'), ('need', 'Need-based'), ('destination', 'Destination/Country'), ('course', 'Course-specific'), ('government', 'Government'), ('partial', 'Partial Tuition'), ('full', 'Full Tuition')], default='merit', max_length=20)),
                ('coverage', models.CharField(help_text='e.g. 25% tuition fee reduction, AUD 10,000', max_length=200)),
                ('coverage_percentage', models.IntegerField(blank=True, help_text='e.g. 25 for 25%', null=True)),
                ('eligibility', models.TextField(help_text='Who is eligible')),
                ('academic_requirement', models.CharField(blank=True, max_length=300)),
                ('eligible_courses', models.CharField(blank=True, help_text="Comma-separated course types or 'All courses'", max_length=500)),
                ('eligible_levels', models.CharField(blank=True, help_text='e.g. Bachelor, Master', max_length=200)),
                ('deadline', models.CharField(blank=True, help_text='e.g. 30 November 2025 or Intake-based', max_length=200)),
                ('intake_deadline', models.BooleanField(default=False, help_text='Deadline tied to intake')),
                ('official_url', models.URLField(help_text='Official scholarship page')),
                ('apply_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='universities.university')),
            ],
            options={
                'ordering': ['-coverage_percentage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('honours', 'Honours'), ('graduate_cert', 'Graduate Certificate'), ('graduate_diploma', 'Graduate Diploma'), ('master', 'Master'), ('phd', 'PhD / Doctorate')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, help_text='e.g. Information Technology, Business', max_length=200)),
                ('duration', models.CharField(help_text='e.g. 3 years, 2 years', max_length=100)),
                ('study_mode', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('online', 'Online'), ('blended', 'Blended')], default='full_time', max_length=20)),
                ('tuition_fee_annual', models.DecimalField(blank=True, decimal_places=2, help_text='Annual fee in AUD', max_digits=10, null=True)),
                ('tuition_fee_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total program fee in AUD', max_digits=10, null=True)),
                ('tuition_note', models.CharField(blank=True, help_text='e.g. per year, 2024 indicative', max_length=200)),
                ('intake_months', models.CharField(help_text='e.g. February, July', max_length=200)),
                ('next_intake', models.CharField(blank=True, max_length=100)),
                ('academic_requirement', models.TextField(help_text="e.g. Minimum 65% in Bachelor's")),
                ('gpa_requirement', models.CharField(blank=True, help_text='e.g. 3.0/4.0 GPA', max_length=100)),
                ('ielts_overall', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ielts_min_band', models.DecimalField(blank=True, decimal_places=1, help_text='Minimum per band', max_digits=3, null=True)),
                ('pte_overall', models.IntegerField(blank=True, null=True)),
                ('toefl_ibt', models.IntegerField(blank=True, null=True)),
                ('career_outcomes', models.TextField(blank=True, help_text='Career pathways')),
                ('course_structure', models.TextField(blank=True, help_text='Brief course structure description')),
                ('description', models.TextField(blank=True)),
                ('official_url', models.URLField(help_text='MANDATORY: Official course page URL')),
                ('apply_url', models.URLField(blank=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ManyToManyField(blank=True, related_name='courses', to='universities.campus')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='universities.university')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='universities.state'),
        ),
        migrations.AddField(
            model_name='campus',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campuses', to='universities.city'),
        ),
        migrations.AddField(
            model_name='campus',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.state'),
        ),
        migrations.AddField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='universities.university'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('slug', 'state')},
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.course')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.university')),
            ],
            options={
                'unique_together': {('session_key', 'university'), ('session_key', 'course')},
            },
        ),
    ]
